// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using BackBAI.Models;

namespace BackBAI.Models
{
    public partial class ideeContext
    {

        [DbFunction("total_likes", "dbo")]
        public static int? total_likes(int? idea_id)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
