// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackBAI.Models;

public partial class Comment
{
    public int Id { get; set; }

    public string? Text { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int FkUsersIdComment { get; set; }

    public int FkIdeaId { get; set; }

    public virtual Idea FkIdea { get; set; }

    public virtual Users FkUsersIdCommentNavigation { get; set; }
}