// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackBAI.Models;

public partial class IdeaGetCategory
{
    public int IdeaId { get; set; }

    public int? CategoryId { get; set; }

    public virtual Category Category { get; set; }

    public virtual Idea Idea { get; set; }
}