// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackBAI.Models;

public partial class Likes
{
    public int FkUsersIdLikes { get; set; }

    public int FkIdeaIdLikes { get; set; }

    public virtual Idea FkIdeaIdLikesNavigation { get; set; }

    public virtual Users FkUsersIdLikesNavigation { get; set; }
}